#!/bin/bash

##
## Usage: mconf-bbb-conf [IP:PORT]
##
## Common sequence of commands:
## sudo dhclient; rm -f mconf-bbb-conf; wget https://raw.github.com/mconf/installation-scripts/master/mconf-bbb-conf; chmod a+x mconf-bbb-conf; ./mconf-bbb-conf
##

HOME=/home/firstuser
BBB_SOURCE=$HOME/dev/source/bigbluebutton
MCONF_REPOS=git://github.com/mconf/bigbluebutton.git
MCONF_BRANCH=current
## http://bash.cyberciti.biz/misc-shell/read-local-ip-address/
HOST=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}'`;
PORT=8888

usage() {
    echo "Mconf-BBB customization script. Applies Mconf customizations on BigBlueButton 0.71a."
    echo "http://code.google.com/p/mconf"
    echo
    echo "   mconf-bbb-conf [-a ADDRESS] [-p BIGBLUEBUTTON_PORT]"
    echo "     [ADDRESS] is the IP or name address of your machine."
    echo "     [BIGBLUEBUTTON_PORT] is the port to be used by BigBlueButton (set it with bbb-conf --setip)."
    echo
    echo "  Other options:"
    echo "    --help, -h                       Shows this help"
    echo
}

while [ $# -gt 0 ]; do
    if [ "$1" = "--help" -o "$1" = "-help" -o "$1" = "-h" ]; then
        usage
        exit 0
    fi
    if [ "$1" = "--address" -o "$1" = "-a" ]; then
        shift
        HOST="${1}"
        shift
        continue
    fi
    if [ "$1" = "--port" -o "$1" = "-p" ]; then
        shift
        PORT="${1}"
        shift
        continue
    fi
    echo
    echo "--------------------------------------------------------------------------------"
    echo "  Unknown command ${1}"
    echo "  Aborting."
    echo "--------------------------------------------------------------------------------"
    echo
    usage
    exit 1
done

echo "Setup Mconf-BBB"
echo
echo "             Address: ${HOST}"
echo "  BigBlueButton Port: ${PORT}"
echo

exit

## http://stackoverflow.com/questions/59838/how-to-check-if-a-directory-exists-in-a-bash-shell-script
if [ ! -d "$BBB_SOURCE" ]
then
    echo '#########################################################'
    echo '# Installing and configuring Mconf BigBlueButton server #'
    echo '#########################################################'

    echo '## Cloning the Mconf repository'
    bbb-conf --checkout $MCONF_REPOS
    cd $BBB_SOURCE
    git fetch origin $MCONF_BRANCH:$MCONF_BRANCH
    git checkout $MCONF_BRANCH
else
    echo '#######################################'
    echo '# Updating Mconf BigBlueButton server #'
    echo '#######################################'

    if [ `grep $MCONF_REPOS $BBB_SOURCE/.git/config | wc -l` -eq 0 ]
    then
        echo '## Error: this is not a Mconf BigBlueButton installation'
        exit 1
    fi

    echo '## Updating the mconf repository'
    cd $BBB_SOURCE
    if [ `git branch | grep "^[ \*] $MCONF_BRANCH$" | wc -l` -eq 0 ]
    then
        git fetch origin $MCONF_BRANCH:$MCONF_BRANCH
    fi
    git checkout $MCONF_BRANCH
    git pull origin $MCONF_BRANCH
fi

sudo apt-get update
sudo apt-get -y install ant

echo '## Adding FLAT_REPO environment variable'
if [ `grep 'export FLAT_REPO' $HOME/.profile | wc -l` -eq 0 ]
then
    echo 'export FLAT_REPO=$HOME/dev/repo' >> $HOME/.profile
fi
source $HOME/.profile > /dev/null

echo '## Setting development environment for the bigbluebutton-client'
bbb-conf --setup-dev client
cd $BBB_SOURCE/bigbluebutton-client
echo '## Configuring the config.xml on the client'
sudo cp resources/config.xml.template /var/www/bigbluebutton/client/conf/config.xml
echo '## Setting IP on BigBlueButton'
sudo bbb-conf --setip $HOST:$PORT
sudo cp /var/www/bigbluebutton/client/conf/config.xml src/conf/config.xml
#sed -i "s/showDebugWindow=\"false\"/showDebugWindow=\"true\"/g" src/conf/config.xml
sed -i "s/<version>VERSION<\/version>/<version> - Mconf Test Server<\/version>/g" src/conf/config.xml
sed -i "s/VERSION/3818/g" src/conf/config.xml
sed -i ':a;N;$!ba;s/\(<module name="SettingsModule"[^>]*\/>\)/<!--\1-->/g' src/conf/config.xml
echo '## Compiling the client'
ant

echo '## Setting development environment for the bigbluebutton-apps'
bbb-conf --setup-dev apps
echo '## Stopping red5'
sudo service red5 stop
cd $BBB_SOURCE/bigbluebutton-apps
echo '## Compiling bigbluebutton-apps'
gradle war deploy

cd $BBB_SOURCE/bbb-voice
echo '## Compiling bbb-voice'
gradle war deploy
sudo sed -i "s/global_codec_prefs=PCMU,G722,PCMA,GSM/global_codec_prefs=speex@16000h@20i,speex@8000h@20i,G7221@32000h,G7221@16000h,G722,PCMU,PCMA,GSM/g" /opt/freeswitch/conf/vars.xml
sudo sed -i "s/outbound_codec_prefs=PCMU,G722,PCMA,GSM/outbound_codec_prefs=speex@16000h@20i,PCMU,PCMA,GSM/g" /opt/freeswitch/conf/vars.xml
#http://code.google.com/p/bigbluebutton/wiki/FAQ#When_I_click_on_the_headset_icon,_nothing_happens?
sudo sed -i "s/sip\.server\.host=.*/sip.server.host=$HOST/g" /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties

echo '## Setting development environment for the bigbluebutton-web'
bbb-conf --setup-dev web
sudo service tomcat6 stop
cd $BBB_SOURCE/bigbluebutton-web
echo '## Downloading the mobile demo'
wget -P web-app/demo/ https://raw.github.com/mconf/mconf-mobile/master/mobile.jsp
rm -f *.war
grails war
SERVLET_DIR=/var/lib/tomcat6/webapps
SALT=$(cat $SERVLET_DIR/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep securitySalt | cut -d= -f2);
sudo rm -rf $SERVLET_DIR/bigbluebutton/ $SERVLET_DIR/bigbluebutton.war
sudo cp bigbluebutton-*.war $SERVLET_DIR/bigbluebutton.war
sudo service tomcat6 start
sudo bbb-conf --setsalt $SALT
sudo bbb-conf --setip $HOST:$PORT

sudo bbb-conf --clean
