#!/bin/bash

# This is the Mconf VM startup script.
# It should be run once (and only once) when you start the VM for the first time.
# The script will configure specific settings for your VM instance.
#
# You can find this file at: https://github.com/mconf/installation-scripts

MCONF_VM_VERSION=0.1    # Mconf VM version
PORT=8888               # Port for BigBlueButton

echo
echo "*******************************************************************************"
echo " Setting up Mconf VM version ${MCONF_VM_VERSION}"
echo "*******************************************************************************"
echo

# get an IP
sudo dhclient
IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -1 | cut -d: -f2 | awk '{print $1}') # local IP got from ifconfig

# Configures BBB in a different IP:port
sudo bbb-conf --setip $IP:$PORT

# Mconf-Wweb configurations. Need user input.
mconf-web-conf --setup-vm $PORT
