#!/bin/bash

# This is the Mconf VM startup script.
# It should be run once (and only once) when you start the VM for the first time.
# The script will configure specific settings for your VM instance.
#
# You can find this file at: https://github.com/mconf/installation-scripts

MCONF_VM_VERSION=0.1
MCONF_WEB_SETUP_CONF=~/dev/source/mconf-web/config/setup_conf.yml
PORT=8888

echo
echo "*******************************************************************************"
echo " Setting up Mconf VM version ${MCONF_VM_VERSION}"
echo "*******************************************************************************"
echo

# get an IP
sudo dhclient
IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -1 | cut -d: -f2 | awk '{print $1}') # local IP got from ifconfig

# configure BBB in a different IP:port
sudo bbb-conf --setip $IP:$PORT

# automatically configure some files in mconf-web
SALT=`bbb-conf --salt | grep "Salt" | sed 's/[[:blank:]]*Salt: //'`
sed -i "s/\(^[[:space:]]*bbb_server_url:\)[^#$]*\(.*\)$/\1 \"http:\/\/${IP}:${PORT}\/bigbluebutton\/api\" \2/g" $MCONF_WEB_SETUP_CONF
sed -i "s/\(^[[:space:]]*bbb_server_salt:\)[^#$]*\(.*\)$/\1 \"${SALT}\" \2/g" $MCONF_WEB_SETUP_CONF
sed -i "s/\(^[[:space:]]*site_domain:\)[^#$]*\(.*\)$/\1 \"${IP}\" \2/g" $MCONF_WEB_SETUP_CONF

# mconf-web configuration that needs user input
mconf-web-conf --setup-vm
