#!/bin/bash

# This is the Mconf VM startup script. The script will configure specific settings for
# your VM instance.
# It should be run once when you start the VM for the first time. Be aware that if you
# run it again you will clean your BBB instance and reset Mconf-Web, dropping and
# recreating the DB.
#
# You can find this file at: https://github.com/mconf/installation-scripts

MCONF_VM_VERSION=0.2    # Mconf VM version
BBB_PORT=8888           # Port for BigBlueButton

echo
echo "*******************************************************************************"
echo " Setting up Mconf VM version ${MCONF_VM_VERSION}"
echo "*******************************************************************************"
echo

# get an IP
sudo dhclient
IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -1 | cut -d: -f2 | awk '{print $1}') # local IP got from ifconfig

# checks for user args
if [[ $# -ge 1 ]]; then
    IP="${1}"
    echo "* Setting IP to ${IP}"
    shift
fi
if [[ $# -ge 1 ]]; then
    BBB_PORT="${1}"
    echo "* Setting BigBlueButton port to ${BBB_PORT}"
    shift
fi

# Configures our customizations over BBB
mconf-bbb-conf $IP:$BBB_PORT

# Mconf-Web configurations. Needs user input.
mconf-web-vm-conf -a $IP -p $BBB_PORT

echo
echo "*******************************************************************************"
echo "  Mconf VM setup complete."
echo "  BigBlueButton at: $IP:$BBB_PORT"
echo "      Mconf-Web at: $IP:80"
echo "*******************************************************************************"
echo
echo "Please, open your browser and access $IP to check if your installation is correct."
echo
